apiVersion: apps/v1beta1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: nginx-app-rs
  labels:
        # Apply this label to Deployment and default
        app: nginx-app-rs
spec:
  # 3 Pods should exist at all times.
  replicas: 2
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: nginx-app-rs
    spec:
      containers:
      - name: nginx-app-rs
        # Run this image
        image: betsol/nginx-app-rs:latest
        ports:
         - containerPort: 80
 
