apiVersion: apps/v1beta1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: nginx-app
spec:
  # 3 Pods should exist at all times.
  replicas: 2
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        # Run this image
        image: betsol/nginx-app:latest
        ports:
         - containerPort: 80
 