apiVersion: apps/v1beta1
kind: Service
metadata:
  # Unique key of the Deployment instance
  name: nginx-app-rs
  labels:
        # Apply this label to Deployment
        app: nginx-app-rs
spec:
  # 3 Pods should exist at all times.
  replicas: 2
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: nginx-app-rs
    spec:
      containers:
      - name: nginx-app-rs
        # Run this image
        image: betsol/nginx-app-rs:v1
        ports:
         - containerPort: 80
 
